In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('datos.xlsx')
df.head()

   ID  Parcial 1  Parcial 2  Parcial 3
0   1         10          0          4
1   2          9          5          7
2   3          9          8          8
3   4          1          8          6
4   5          6          9          5

In [3]:
df.describe()

              ID  Parcial 1  Parcial 2  Parcial 3
count  35.000000  35.000000  35.000000  35.000000
mean   18.000000   5.628571   5.342857   4.885714
std    10.246951   3.254732   3.271471   3.122701
min     1.000000   0.000000   0.000000   0.000000
25%     9.500000   3.000000   3.000000   2.000000
50%    18.000000   6.000000   5.000000   5.000000
75%    26.500000   9.000000   8.500000   7.000000
max    35.000000  10.000000   9.000000  10.000000

In [6]:
print(df['Parcial 1'].mean())
print(df['Parcial 1'].min())
print(df['Parcial 1'].max())

5.628571428571429
0
10

In [9]:
df['prom'] = df[['Parcial 1', 'Parcial 2', 'Parcial 3']].mean(axis=1)
df['estatus'] = np.where(df['prom'] >= 7, 'Aprobado', 'Reprobado')
df

    ID  Parcial 1  Parcial 2  Parcial 3      prom    estatus
0    1         10          0          4  4.666667  Reprobado
1    2          9          5          7  7.000000   Aprobado
2    3          9          8          8  8.333333   Aprobado
3    4          1          8          6  5.000000  Reprobado
4    5          6          9          5  6.666667  Reprobado
5    6          9          6          2  5.666667  Reprobado
6    7          6          1          7  4.666667  Reprobado
7    8          1          8         10  6.333333  Reprobado
8    9          1          0         10  3.666667  Reprobado
9   10          4          9          5  6.000000  Reprobado
10  11          7          5          3  5.000000  Reprobado
11  12          3          9          2  4.666667  Reprobado
12  13          4          9          3  5.333333  Reprobado
13  14          2          9          2  4.333333  Reprobado
14  15          7          4          2  4.333333  Reprobado
15  16          3          6          5  4.666667  Reprobado
16  17          8          0          7  5.000000  Reprobado
17  18          7          1          1  3.000000  Reprobado
18  19          2          9          9  6.666667  Reprobado
19  20          3          0          1  1.333333  Reprobado
20  21          8          9          3  6.666667  Reprobado
21  22          9          5         10  8.000000   Aprobado
22  23          4          5          9  6.000000  Reprobado
23  24          3          5          7  5.000000  Reprobado
24  25          0          9          5  4.666667  Reprobado
25  26          1          5          1  2.333333  Reprobado
26  27          2          3         10  5.000000  Reprobado
27  28         10          8          4  7.333333   Aprobado
28  29         10          3          1  4.666667  Reprobado
29  30          8          2          8  6.000000  Reprobado
30  31          9          6          5  6.666667  Reprobado
31  32         10          9          4  7.666667   Aprobado
32  33          6          0          5  3.666667  Reprobado
33  34          9          8          0  5.666667  Reprobado
34  35          6          4          0  3.333333  Reprobado